name: 'Lighthouse CI Action'
description: 'Audit URLs using Lighthouse and test performance with Lighthouse CI'
inputs:
  urls:
    description: 'List of URL(s) to analyze'
runs:
  using: 'node16'
  main: 'src/index.js'
